vim.g.mapleader = " "

require('plugins')
require('options')
require('lualine-config')
require('bufferline-config')
require('nvim-tree-config')
require('autopairs-config')
require('keybindings')
require('comment-config')
require('whichkey-config')
require('telescope-config')
require('colorizer-config')
require('dashboard-config')
require('blankline-config')
require('format-config')
require('toggleterm-config')
require('lsp')
require('treesitter-config')
vim.cmd('colorscheme dracula')
